### ISSUE TITLE
Support custom Procfile

### ISSUE THREAD

**Issue by jincod** [jincod/dotnetcore-buildpack#27]

**Comment by WilhelmKleuSage** [comment]
Opened a PR with basic functionality for this: https://github.com/jincod/dotnetcore-buildpack/pull/28
Please have a look.

**Comment by jincod** [comment]
Hi @WilhelmKleuSage 

Thank you for your contribution!

I'll review it

**Comment by WilhelmKleuSage** [comment]
Great. Thanks.
I just noticed a few issues (publishing everything to a single directory). I am going to change it to publish each one independently and then also automatically add the cd to heroku_output.

**Comment by jincod** [comment]
Hi @JA-AmbosImmo 

I don't have enough time to test it. 

What do you mean `support different environments`?

**Comment by JA-AmbosImmo** [comment]
Since the procfile configuration is overwritten during build, I cannot add the asp environment variable. Is there a workaround to do this? I cannot use appsettings.json in different environments because in heroku the environment variable can only be set to production as default

**Comment by jincod** [comment]
@JA-AmbosImmo You can set env variable on Settings tab at Heroku ![image](https://user-images.githubusercontent.com/1294432/42128654-085e2548-7cca-11e8-9b19-c60a65bb60d5.png)

**Comment by JA-AmbosImmo** [comment]
Is this the same as passing it with the Procfile?

**Comment by jincod** [comment]
@JA-AmbosImmo yes, you find more info here https://devcenter.heroku.com/articles/config-vars

**Comment by JA-AmbosImmo** [comment]
Thank you very much!

**Comment by xt449** [comment]
Not sure if I should put this here or make a new issue for it. I'm trying to setup a worker dyno for my app instead of web, but from the articles I read, that needs to be defined in the procfile? So I'll have to wait for custom procfiles for this buildpack, correct?

**Comment by jincod** [comment]
Hi @xt449,

We 've already added support of custom procfile here https://github.com/jincod/dotnetcore-buildpack/pull/53. Could you please test it for you scenario?

**Comment by xt449** [comment]
Alright, I got that working now. I never used custom profiles before so I was not sure how to do it, but this was really easy to get working. The only slight issue I may have is that is appears to take longer to verify the deployment, but I think this is on Heroku's end?

Here's another question though, how can I get this to work without needing the Startup class?

**Comment by jincod** [comment]
Hi @xt449,

> The only slight issue I may have is that is appears to take longer to verify the deployment, but I think this is on Heroku's end?

Unfortunately I didn't understand what do you mean?

> Here's another question though, how can I get this to work without needing the Startup class?

You can set `PROJECT_FILE` environment variable at Heroku and it will use instead of using `Startup.cs` (https://github.com/jincod/dotnetcore-buildpack/blob/master/bin/compile#L40)

**Comment by xt449** [comment]
Sorry. I meant that it takes git longer to finish. Specifically for the remote to send `Verifying deploy... done.`

**Comment by jincod** [comment]
Understood. It's Heroku workflow.

For example, you can see log output for `git push heroku master` for Rails application https://devcenter.heroku.com/articles/getting-started-with-rails5#deploy-your-application-to-heroku

**Comment by xt449** [comment]
Alright just wanted to follow up that it seems to be working.
Setting the PROJECT_FILE to the startup class I want doesn't seem to work for me :
I lost the git log for that one...
However I still seem to need Startup.cs :
`Remote: 
Remote: -----> App not compatible with buildpack: https://github.com/jincod/dotnetcore-buildpack.git        
Remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure        
Remote: 
Remote:  !     Push failed        
Remote: Verifying deploy...
Remote: 
Remote: !	Push rejected to bot-vohelpyo.        
Remote: 
Error: failed to push some refs to 'https://git.heroku.com/bot-vohelpyo.git'
Error encountered while pushing to the remote repository: rejected master -> master (pre-receive hook declined)`

I will give more information on this tomorrow. This is poorly written since I just typed this up before going to sleep.
