### ISSUE TITLE
Add section about EF migrations to README

### ISSUE THREAD

**Issue by jincod** [jincod/dotnetcore-buildpack#46]

**Comment by welkie** [comment]
Will write about this and send a PR soon since I got to work with this recently.

**Comment by Tochemey** [comment]
What I have done to run automatically migration is to do from code in the Startup.cs class in the Configure function with the following code:

```
            using (var serviceScope = app.ApplicationServices.GetService<IServiceScopeFactory>().CreateScope())
            {
                var context = serviceScope.ServiceProvider.GetRequiredService<DataContext>();
                context.Database.Migrate();
            }
```
By these I had at five projects on heroku running.

**Comment by welkie** [comment]
@Tochemey This worked for me too. However, there is an alternative style suggested by @jincod that does not involve changing the code. However, @friism pointed out in https://github.com/jincod/dotnetcore-buildpack/pull/47 that this may cause an unnecessary dependency on the SDK and it doesn't necessarily fall into the "Heroku way" of doings things which is to use [Release Phases](https://devcenter.heroku.com/articles/release-phase). This way, modifying the source code, also doesn't fall into that "Heroku way".

I also think doing it in the code is a bit of a problem unless the code runs conditionally based on an environment variable, since it causes the migration running behavior to exist at a low level instead of based on configuration.

**Comment by jincod** [comment]
Implemented at https://github.com/jincod/dotnetcore-buildpack/pull/47

Many thanks to @welkie
