### ISSUE TITLE
Help with angular template

### ISSUE THREAD

**Issue by viniciuslln** [jincod/dotnetcore-buildpack#51]
Hi,
I create a project with dotnet cli with:

> dotnet new angular -o superangular

I tried to deploy to heroku following README instructions:

> heroku buildpacks:set https://github.com/jincod/dotnetcore-buildpack
> heroku buildpacks:add --index 1 heroku/nodejs

This template runs npm after buid but the command fails then push are rejected:

```
remote:   /bin/sh: 2: /tmp/tmp7eb1f23629a34e758294b97088a44e37.exec.cmd: npm: not found
remote: /tmp/build_6a10bba1cca1756c15bb8d823338d489/superangular.csproj(38,5): error MSB3073: The command "npm install" exited with code 127.
remote:  !     Push rejected, failed to compile ASP.NET Core app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
```

If I change the order of the buildpack, nodejs fails and dotnet doesn't run:

```
remote: -----> App not compatible with buildpack: https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/nodejs.tgz
remote:        Node.js: package.json not found in application root
remote:
remote:        More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
remote:
remote:  !     Push failed
```

Is there anything I can do?

**Comment by jincod** [comment]
Hi @viniciuslln 

Correct buildpack order:
![image](https://user-images.githubusercontent.com/1294432/42720992-9abae364-874b-11e8-9e88-f271c7523697.png)

`dotnet new angular` create `ClientApp\package.json` at nested folder.

You can do workaround: add empty `package.json` to project root, for example, `npm init -y`, because `heroku/nodejs` requires `package.json` located at project root, 

P.S.: Here (https://github.com/jincod/AspNet5DemoApp) you can see my Asp.Net Core project with React.js which deploys to Heroku
